name: ubuntu-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Restore build/ext
        id: cache-ext-restore
        uses: actions/cache/restore@v3
        #if: ${{ !env.ACT }}
        with:
          path: |
            build/ext
          key: ${{ runner.os }}-ext

      - name: printenv
        run: |
          touch ~/GH_ACT_TOKEN.txt
          printenv && sudo apt-get update && \
          sudo apt-get install -y python3 make autoconf automake libtool build-essential gettext

      - name: make
        run: make

      - name: Save build/ext
        id: cache-ext-save
        uses: actions/cache/save@v3
        #if: ${{ !env.ACT }}
        with:
          path: |
            build/ext
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

